import {
  appendHistory,
  buildCacheKey,
  getCache,
  getCacheTtlSeconds,
  setCache,
} from "@/lib/cache";
import { FILE_FORMAT_LOOKUP } from "@/lib/data/presets";
import { env, featureAvailability } from "@/lib/env";
import {
  searchGoogleCse,
  type GoogleCseRequest,
  type SerpApiAccessContext,
} from "@/lib/api/google-cse";

import { extractTextWithOcr, loadImage, type LoadedImage } from "@/lib/image";
import {
  ALL_DISCOVERY_FILE_TYPES,
  buildAdaptiveUsernameQueries,
  buildBatchQueries,
  buildQueriesFromIdentifiers,
  buildSearchQuery,
  buildTargetSweepQueries,
  USERNAME_PRESENCE_SITES,
} from "@/lib/query";
import type {
  AutoGeneratedQuery,
  BatchDiscoveryFinding,
  BatchDiscoveryRequest,
  BatchDiscoveryResponse,
  ExtractedIdentifier,
  ImageAnalysisRequest,
  ImageAnalysisResponse,
  SearchQueryResponse,
  SearchResultItem,
  StructuredQueryInput,
  SweepSection,
  SweepTargetType,
  TargetSweepRequest,
  TargetSweepResponse,
} from "@/lib/types/osint";

type HistoryKind =
  | "structured-query"
  | "batch-discovery"
  | "image-analysis"
  | "target-sweep";

type JsonRecord = Record<string, unknown>;

const DEFAULT_SEARCH_PAGE_SIZE = 10;
const DEFAULT_BATCH_PAGE_SIZE = 5;
const MAX_RELATED_IMAGE_QUERIES = 4;
const MAX_ADAPTIVE_SWEEP_QUERIES = 6;
const MAX_EXPANSION_SOURCE_RESULTS = 8;
const DEFAULT_EXPANSION_ROUNDS = 1;
const DEFAULT_EXPANSION_QUERIES_PER_ROUND = 2;
const DEFAULT_EXPANSION_MIN_SCORE = 0.32;
const DEFAULT_EXPANSION_REQUEST_BUDGET = 6;
const DEFAULT_EXPANSION_SESSION_BUDGET = 30;
const EXPANSION_BUDGET_TTL_SECONDS = 60 * 60 * 24;

type VisionRawPayload = {
  summary: string;
  entities: Array<{
    type: string;
    value: string;
    confidence: number;
    notes?: string;
    sourceText: string;
  }>;
  suggestedQueries: string[];
  notableText: string[];
  raw?: unknown;
};

type QueryExpansionPayload = {
  queries: Array<{
    query: string;
    reason?: string;
    confidence?: number;
  }>;
};

type RankedExpansionQuery = {
  query: string;
  reason?: string;
  confidence?: number;
  score: number;
};

type ExpansionBudgetState = {
  used: number;
};

function nowIso() {
  return new Date().toISOString();
}

function normalizeWhitespace(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function normalizeCsvLikeList(value?: string | string[]) {
  if (!value) {
    return [];
  }

  const list = Array.isArray(value) ? value : value.split(/[,\n]/g);

  return Array.from(
    new Set(list.map((item) => normalizeWhitespace(item)).filter(Boolean)),
  );
}

function normalizeTarget(value: string) {
  return normalizeWhitespace(value);
}

function isDomainLike(value: string) {
  return /^[a-z0-9.-]+\.[a-z]{2,}$/i.test(value.trim());
}

function inferSweepType(target: string): SweepTargetType {
  const value = target.trim();

  if (value.includes("@")) {
    return "email";
  }

  if (isDomainLike(value)) {
    return "domain";
  }

  if (/^[a-z0-9._-]{3,}$/i.test(value) && !/\s/.test(value)) {
    return "username";
  }

  return "name";
}

function safeNumber(value: unknown, fallback = 0) {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }

  return fallback;
}

function mapSearchResultItem(item: {
  title?: string;
  link?: string;
  snippet?: string;
  displayLink?: string;
  formattedUrl?: string;
  mime?: string;
  fileFormat?: string;
}): SearchResultItem {
  const rawLink = typeof item.link === "string" ? item.link : "";

  return {
    title: typeof item.title === "string" ? item.title : "Untitled result",
    link: rawLink,
    snippet: typeof item.snippet === "string" ? item.snippet : "",
    displayLink:
      typeof item.displayLink === "string" ? item.displayLink : undefined,
    formattedUrl:
      typeof item.formattedUrl === "string" ? item.formattedUrl : undefined,
    mime: typeof item.mime === "string" ? item.mime : undefined,
    fileFormat:
      typeof item.fileFormat === "string" ? item.fileFormat : undefined,
    filetype: inferFiletypeFromResult({
      link: rawLink,
      fileFormat:
        typeof item.fileFormat === "string" ? item.fileFormat : undefined,
      mime: typeof item.mime === "string" ? item.mime : undefined,
    }),
  };
}

function inferFiletypeFromResult(input: {
  link?: string;
  mime?: string;
  fileFormat?: string;
}) {
  const link = input.link?.toLowerCase() ?? "";

  const byLink = link.match(/\.([a-z0-9]{2,8})(?:$|[?#])/i)?.[1];
  if (byLink) {
    return byLink;
  }

  const fileFormat = input.fileFormat?.toLowerCase() ?? "";
  const byFormat = fileFormat.match(
    /\b(pdf|docx|xlsx|pptx|txt|csv|json|yaml|xml|sql|log|env|zip|tar)\b/i,
  )?.[1];
  if (byFormat) {
    return byFormat.toLowerCase();
  }

  const mime = input.mime?.toLowerCase() ?? "";
  if (mime.includes("pdf")) return "pdf";
  if (mime.includes("json")) return "json";
  if (mime.includes("xml")) return "xml";
  if (mime.includes("zip")) return "zip";
  if (mime.includes("text/plain")) return "txt";

  return undefined;
}

function toIdentifierType(type: string): ExtractedIdentifier["type"] {
  switch (type) {
    case "name":
    case "username":
    case "email":
    case "domain":
    case "phone":
    case "organization":
      return type;
    default:
      return "other";
  }
}

function visionFallbackFromOcr(ocrLines: string[]): VisionRawPayload {
  return {
    summary: "Gemini vision is unavailable. OCR-only mode completed.",
    entities: [],
    suggestedQueries: buildQueriesFromIdentifiers(
      normalizeCsvLikeList(ocrLines).slice(0, 8),
    ),
    notableText: ocrLines.slice(0, 12),
  };
}

function toGeminiInlineData(image: LoadedImage) {
  if (Buffer.isBuffer(image.source)) {
    return {
      mimeType: image.mimeType || "image/png",
      data: image.source.toString("base64"),
    };
  }

  const value = image.source.trim();
  const match = value.match(/^data:(.+?);base64,(.+)$/i);
  if (match) {
    const [, mimeType, data] = match;
    return {
      mimeType,
      data,
    };
  }

  return {
    mimeType: image.mimeType || "image/png",
    data: value,
  };
}

function stripCodeFence(value: string) {
  const trimmed = value.trim();
  const jsonFence = trimmed.match(/^```json\s*([\s\S]*?)\s*```$/i);
  if (jsonFence?.[1]) {
    return jsonFence[1].trim();
  }

  const genericFence = trimmed.match(/^```\s*([\s\S]*?)\s*```$/i);
  if (genericFence?.[1]) {
    return genericFence[1].trim();
  }

  return trimmed;
}

async function extractGeminiText(response: unknown): Promise<string> {
  const candidate = response as {
    text?: string | (() => string | Promise<string>);
    candidates?: Array<{
      content?: {
        parts?: Array<{ text?: string }>;
      };
    }>;
  };

  if (typeof candidate.text === "string") {
    return candidate.text;
  }

  if (typeof candidate.text === "function") {
    const resolved = await candidate.text();
    if (typeof resolved === "string") {
      return resolved;
    }
  }

  const parts = candidate.candidates?.[0]?.content?.parts ?? [];
  const text = parts
    .map((part) => part.text)
    .filter((partText): partText is string => typeof partText === "string")
    .join("\n")
    .trim();

  return text;
}

const geminiVisionSchema = {
  type: "object",
  properties: {
    summary: { type: "string" },
    entities: {
      type: "array",
      items: {
        type: "object",
        properties: {
          type: {
            type: "string",
            enum: [
              "name",
              "username",
              "email",
              "domain",
              "phone",
              "organization",
              "other",
            ],
          },
          value: { type: "string" },
          confidence: { type: "number" },
          notes: { type: "string" },
          sourceText: { type: "string" },
        },
        required: ["type", "value", "confidence", "sourceText"],
      },
    },
    suggestedQueries: {
      type: "array",
      items: { type: "string" },
    },
    notableText: {
      type: "array",
      items: { type: "string" },
    },
  },
  required: ["summary", "entities", "suggestedQueries", "notableText"],
} as const;

async function runGeminiVision(
  image: LoadedImage,
  ocrLines: string[],
): Promise<VisionRawPayload> {
  if (!env.GEMINI_API_KEY) {
    return visionFallbackFromOcr(ocrLines);
  }

  const { GoogleGenAI } = await import("@google/genai");
  const client = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });
  const inlineData = toGeminiInlineData(image);

  const prompt = [
    "You are an OSINT analyst.",
    "Analyze the image and extract investigation pivots.",
    "Focus on logos, people, organizations, places, usernames, emails, domains, phone numbers, and other actionable clues.",
    "Use OCR hints below if useful:",
    ocrLines.slice(0, 30).join("\n") || "(no OCR text)",
    "Return strict JSON only using the schema.",
  ].join("\n\n");

  const response = await client.models.generateContent({
    model: "gemini-2.5-flash",
    contents: [
      {
        role: "user",
        parts: [
          { text: prompt },
          {
            inlineData: {
              mimeType: inlineData.mimeType,
              data: inlineData.data,
            },
          },
        ],
      },
    ],
    config: {
      responseMimeType: "application/json",
      responseSchema: geminiVisionSchema,
      temperature: 0.2,
    },
  });

  const text = stripCodeFence(await extractGeminiText(response));
  if (!text) {
    throw new Error("Gemini returned an empty vision response.");
  }

  const parsed = JSON.parse(text) as VisionRawPayload;
  return {
    summary: parsed.summary,
    entities: Array.isArray(parsed.entities) ? parsed.entities : [],
    suggestedQueries: Array.isArray(parsed.suggestedQueries)
      ? parsed.suggestedQueries
      : [],
    notableText: Array.isArray(parsed.notableText) ? parsed.notableText : [],
    raw: parsed,
  };
}

function normalizeExpandedQuery(value: string): string {
  return normalizeWhitespace(value).replace(/[\u0000-\u001F]+/g, "").trim();
}

function clampNumber(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}

function tokenizeForScoring(value: string): Set<string> {
  const tokens = value
    .toLowerCase()
    .split(/[^a-z0-9._:-]+/g)
    .map((token) => token.trim())
    .filter((token) => token.length >= 3);

  return new Set(tokens);
}

function scoreExpandedQuery(input: {
  seedQuery: string;
  query: string;
  confidence?: number;
}): number {
  const seedTokens = tokenizeForScoring(input.seedQuery);
  const queryTokens = tokenizeForScoring(input.query);

  const overlapCount = Array.from(queryTokens).filter((token) => seedTokens.has(token)).length;
  const overlap = seedTokens.size > 0 ? overlapCount / seedTokens.size : 0;

  const operatorCount = (input.query.match(/\b(site|inurl|intitle|intext|filetype):/gi) || [])
    .length;
  const operatorSignal = clampNumber(operatorCount / 3, 0, 1);

  const tokenCount = queryTokens.size;
  const lengthSignal = tokenCount >= 3 && tokenCount <= 18 ? 1 : tokenCount <= 24 ? 0.6 : 0.35;

  const confidence = clampNumber(input.confidence ?? 0.5, 0, 1);

  return clampNumber(
    overlap * 0.45 + operatorSignal * 0.2 + lengthSignal * 0.2 + confidence * 0.15,
    0,
    1,
  );
}

function expansionBudgetKey(scopeKey: string): string {
  return `ghostdork:budget:expansion:${scopeKey}`;
}

async function getExpansionBudgetUsage(scopeKey?: string): Promise<number> {
  if (!scopeKey) {
    return 0;
  }

  const cached = await getCache<ExpansionBudgetState>(expansionBudgetKey(scopeKey));
  return cached?.used ?? 0;
}

async function setExpansionBudgetUsage(scopeKey: string, used: number): Promise<void> {
  await setCache(
    expansionBudgetKey(scopeKey),
    { used },
    { ttlSeconds: EXPANSION_BUDGET_TTL_SECONDS },
  );
}

function extractExpansionSeed(items: SearchResultItem[]): string {
  return items
    .slice(0, MAX_EXPANSION_SOURCE_RESULTS)
    .map((item, index) => {
      const title = item.title || "Untitled";
      const snippet = item.snippet || "";
      const link = item.link || "";
      return `${index + 1}. ${title}\nURL: ${link}\nSnippet: ${snippet}`;
    })
    .join("\n\n");
}

async function suggestExpandedQueriesFromResults(input: {
  seedQuery: string;
  round: number;
  items: SearchResultItem[];
  maxQueries: number;
  seenQueries: Set<string>;
}): Promise<RankedExpansionQuery[]> {
  if (!env.GEMINI_API_KEY || input.items.length === 0 || input.maxQueries <= 0) {
    return [];
  }

  const { GoogleGenAI } = await import("@google/genai");
  const client = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });

  const prompt = [
    "You are an OSINT query expansion assistant.",
    "Generate broader but still relevant Google dork queries from initial search results.",
    "Rules:",
    "- Return only high-signal queries for investigation pivots.",
    "- Prefer domain, organization, username, document, and breach-intent pivots.",
    "- Do not include illegal instructions or exploit guidance.",
    "- Avoid duplicates and near-duplicates.",
    `- Return at most ${Math.max(input.maxQueries * 3, input.maxQueries)} queries.`,
    "",
    `Round: ${input.round}`,
    `Seed query: ${input.seedQuery}`,
    "",
    "Search result context:",
    extractExpansionSeed(input.items),
    "",
    "Return strict JSON with shape: {\"queries\":[{\"query\":\"...\",\"reason\":\"...\",\"confidence\":0.0}]}",
  ].join("\n");

  const response = await client.models.generateContent({
    model: "gemini-2.5-flash",
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: "object",
        properties: {
          queries: {
            type: "array",
            items: {
              type: "object",
              properties: {
                query: { type: "string" },
                reason: { type: "string" },
                confidence: { type: "number" },
              },
              required: ["query"],
            },
          },
        },
        required: ["queries"],
      },
      temperature: 0.35,
    },
  });

  const text = stripCodeFence(await extractGeminiText(response));
  if (!text) {
    return [];
  }

  const parsed = JSON.parse(text) as QueryExpansionPayload;
  const ranked = (Array.isArray(parsed.queries) ? parsed.queries : []).reduce<
    RankedExpansionQuery[]
  >((acc, entry) => {
      const normalizedQuery = normalizeExpandedQuery(entry.query);
      if (!normalizedQuery || input.seenQueries.has(normalizedQuery)) {
        return acc;
      }

      acc.push({
        query: normalizedQuery,
        reason: entry.reason,
        confidence: entry.confidence,
        score: scoreExpandedQuery({
          seedQuery: input.seedQuery,
          query: normalizedQuery,
          confidence: entry.confidence,
        }),
      });

      return acc;
    }, []);

  ranked.sort((a, b) => b.score - a.score);

  return ranked.slice(0, Math.max(input.maxQueries * 3, input.maxQueries));
}

function dedupeResults(items: SearchResultItem[]) {
  const seen = new Set<string>();

  return items.filter((item) => {
    const key = item.link || `${item.title}:${item.snippet}`;
    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

function dedupeFindings(items: BatchDiscoveryFinding[]) {
  const seen = new Set<string>();

  return items.filter((item) => {
    const key = `${item.extension}:${item.link}`;
    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

function normalizeSiteHost(value: string) {
  return value.replace(/^www\./i, "").trim().toLowerCase();
}

function extractHostname(value?: string) {
  if (!value) {
    return null;
  }

  try {
    return normalizeSiteHost(new URL(value).hostname);
  } catch {
    return null;
  }
}

function extractAdaptiveSitesFromResults(
  items: SearchResultItem[],
  excludedSites: string[],
) {
  const excluded = new Set(excludedSites.map(normalizeSiteHost));

  return Array.from(
    new Set(
      items
        .flatMap((item) => [
          extractHostname(item.link),
          item.displayLink ? normalizeSiteHost(item.displayLink) : null,
        ])
        .filter((site): site is string => Boolean(site && site.includes(".")))
        .filter((site) => !excluded.has(site)),
    ),
  );
}

function toStructuredRequest(
  input: StructuredQueryInput,
  start = 1,
  num = DEFAULT_SEARCH_PAGE_SIZE,
): GoogleCseRequest {
  return {
    query: normalizeWhitespace(input.freeText ?? ""),
    operators: {
      site: normalizeCsvLikeList(input.site),
      inurl: normalizeCsvLikeList(input.inurl),
      intitle: normalizeCsvLikeList(input.intitle),
      intext: normalizeCsvLikeList(input.intext),
      filetype: normalizeCsvLikeList(input.filetype),
      before: normalizeCsvLikeList(input.before),
      after: normalizeCsvLikeList(input.after),
    },
    exactTerms: normalizeCsvLikeList(input.exactTerms),
    excludeTerms: normalizeCsvLikeList(input.excludeTerms),
    start,
    num,
  };
}

export async function persistHistory(
  kind: HistoryKind,
  title: string,
  query: string,
  payload: JsonRecord,
  target?: string,
  tags?: string[],
) {
  await appendHistory({
    type: kind,
    title,
    query,
    target,
    tags,
    ttlSeconds: getCacheTtlSeconds(),
    payload,
  });
}

export async function runStructuredQuery(
  input: StructuredQueryInput,
  options?: {
    start?: number;
    num?: number;
    cache?: boolean;
    adaptive?: boolean;
    serpApiContext?: SerpApiAccessContext;
    expansionRounds?: number;
    expansionQueriesPerRound?: number;
    expansionMinScore?: number;
    expansionRequestBudget?: number;
    expansionSessionBudget?: number;
    expansionBudgetScopeKey?: string;
  },
): Promise<SearchQueryResponse> {
  const request = toStructuredRequest(
    input,
    options?.start ?? 1,
    options?.num ?? DEFAULT_SEARCH_PAGE_SIZE,
  );

  const query = buildSearchQuery({
    operators: {
      site: request.operators?.site,
      inurl: request.operators?.inurl,
      intitle: request.operators?.intitle,
      intext: request.operators?.intext,
      filetype: request.operators?.filetype,
      before: request.operators?.before,
      after: request.operators?.after,
    },
    freeText: request.query,
  });

  const cacheKey = buildCacheKey("search:query", {
    request,
    query,
    serpApiContext: options?.serpApiContext ?? "other",
    adaptive: options?.adaptive !== false,
    expansion: {
      rounds: options?.expansionRounds ?? 0,
      perRound: options?.expansionQueriesPerRound ?? 0,
      minScore: options?.expansionMinScore,
    },
  });

  const shouldUseCache =
    options?.cache !== false &&
    ((options?.expansionRounds ?? DEFAULT_EXPANSION_ROUNDS) <= 0 ||
      (options?.serpApiContext ?? "other") !== "build-query");

  if (shouldUseCache) {
    const cached = await getCache<SearchQueryResponse>(cacheKey);
    if (cached) {
      return {
        ...cached,
        meta: {
          ...cached.meta,
          cached: true,
          source: cached.meta.source === "mock" ? "mock" : "cache",
          cacheKey,
        },
      };
    }
  }

  if (!query) {
    return {
      meta: {
        query: "",
        totalResults: 0,
        startIndex: request.start ?? 1,
        count: request.num ?? DEFAULT_SEARCH_PAGE_SIZE,
        cached: false,
        cacheKey,
        source: "mock",
        generatedAt: nowIso(),
      },
      items: [],
    };
  }

  const serpApiContext = options?.serpApiContext ?? "other";

  if (!featureAvailability.googleSearch) {
    const mockResponse: SearchQueryResponse = {
      meta: {
        query,
        totalResults: 0,
        startIndex: request.start ?? 1,
        count: request.num ?? DEFAULT_SEARCH_PAGE_SIZE,
        cached: false,
        cacheKey,
        source: "mock",
        generatedAt: nowIso(),
      },
      items: [],
    };

    if (shouldUseCache) {
      await setCache(cacheKey, mockResponse as unknown as JsonRecord);
    }

    await persistHistory(
      "structured-query",
      "Structured query",
      query,
      mockResponse as unknown as JsonRecord,
    );

    return mockResponse;
  }

  const response = await searchGoogleCse(request, undefined, serpApiContext);

  const result: SearchQueryResponse = {
    meta: {
      query: response.searchTerms || query,
      totalResults: safeNumber(response.totalResults),
      startIndex: safeNumber(response.startIndex, 1),
      count: safeNumber(response.count, DEFAULT_SEARCH_PAGE_SIZE),
      searchTime: safeNumber(response.searchTime),
      cached: false,
      cacheKey,
      source: "google",
      generatedAt: nowIso(),
    },
    items: dedupeResults(response.items.map(mapSearchResultItem)),
  };

  const expansionRounds = Math.max(
    0,
    Math.min(options?.expansionRounds ?? DEFAULT_EXPANSION_ROUNDS, 2),
  );
  const expansionQueriesPerRound = Math.max(
    1,
    Math.min(options?.expansionQueriesPerRound ?? DEFAULT_EXPANSION_QUERIES_PER_ROUND, 4),
  );
  const canExpandQueries =
    expansionRounds > 0 &&
    serpApiContext === "build-query" &&
    featureAvailability.googleSearch &&
    featureAvailability.vision;
  const expansionMinScore = clampNumber(
    options?.expansionMinScore ?? DEFAULT_EXPANSION_MIN_SCORE,
    0,
    1,
  );
  const expansionRequestBudget = clampNumber(
    options?.expansionRequestBudget ?? DEFAULT_EXPANSION_REQUEST_BUDGET,
    1,
    12,
  );
  const expansionSessionBudget = clampNumber(
    options?.expansionSessionBudget ?? DEFAULT_EXPANSION_SESSION_BUDGET,
    5,
    200,
  );

  if (canExpandQueries) {
    const seenQueries = new Set<string>([query]);
    const generatedQueries: string[] = [];
    const executedQueries: NonNullable<SearchQueryResponse["aiExpansion"]>["executedQueries"] = [];
    const skippedQueries: NonNullable<SearchQueryResponse["aiExpansion"]>["skippedQueries"] = [];
    let roundSeedItems = [...result.items];
    let remainingRequestBudget = expansionRequestBudget;
    const scopeKey = options?.expansionBudgetScopeKey;
    let usedSessionBudget = await getExpansionBudgetUsage(scopeKey);
    let remainingSessionBudget = Math.max(0, expansionSessionBudget - usedSessionBudget);

    for (let round = 1; round <= expansionRounds; round += 1) {
      const maxRoundBudget = Math.min(
        expansionQueriesPerRound,
        remainingRequestBudget,
        remainingSessionBudget,
      );

      if (maxRoundBudget <= 0) {
        skippedQueries?.push({
          query: "",
          reason:
            remainingRequestBudget <= 0
              ? "Per-request expansion budget reached."
              : "Session expansion budget reached.",
        });
        break;
      }

      let rankedRoundQueries: RankedExpansionQuery[] = [];

      try {
        rankedRoundQueries = await suggestExpandedQueriesFromResults({
          seedQuery: query,
          round,
          items: roundSeedItems,
          maxQueries: maxRoundBudget,
          seenQueries,
        });
      } catch (error) {
        console.error("Gemini query expansion failed for round", round, error);
      }

      const acceptedRoundQueries = rankedRoundQueries
        .filter((candidate) => {
          if (candidate.score >= expansionMinScore) {
            return true;
          }

          skippedQueries?.push({
            query: candidate.query,
            score: Number(candidate.score.toFixed(3)),
            reason: "Below configured minimum expansion score.",
          });
          return false;
        })
        .slice(0, maxRoundBudget);

      if (acceptedRoundQueries.length === 0) {
        break;
      }

      const roundResults = await Promise.all(
        acceptedRoundQueries.map(async (candidate) => {
          const expandedQuery = candidate.query;
          seenQueries.add(expandedQuery);
          generatedQueries.push(expandedQuery);

          const expansionResponse = await searchGoogleCse(
            {
              query: expandedQuery,
              start: 1,
              num: options?.num ?? DEFAULT_BATCH_PAGE_SIZE,
            },
            undefined,
            "build-query",
          );

          const mappedResults = dedupeResults(
            expansionResponse.items.map(mapSearchResultItem),
          );

          return {
            site: "ai-expansion",
            query: expandedQuery,
            results: mappedResults,
            totalResults: safeNumber(expansionResponse.totalResults),
          };
        }),
      );

      executedQueries.push(...roundResults);
      remainingRequestBudget = Math.max(0, remainingRequestBudget - roundResults.length);
      usedSessionBudget += roundResults.length;
      remainingSessionBudget = Math.max(0, expansionSessionBudget - usedSessionBudget);
      roundSeedItems = roundResults.flatMap((entry) => entry.results);
      if (roundSeedItems.length === 0) {
        break;
      }
    }

    if (scopeKey && usedSessionBudget > 0) {
      await setExpansionBudgetUsage(scopeKey, usedSessionBudget);
    }

    if (generatedQueries.length > 0) {
      result.aiExpansion = {
        rounds: expansionRounds,
        minScore: expansionMinScore,
        requestBudget: expansionRequestBudget,
        sessionBudget: scopeKey ? expansionSessionBudget : undefined,
        sessionRemaining: scopeKey ? remainingSessionBudget : undefined,
        generatedQueries,
        executedQueries,
        skippedQueries: skippedQueries?.length ? skippedQueries : undefined,
      };
    } else if (skippedQueries?.length) {
      result.aiExpansion = {
        rounds: expansionRounds,
        minScore: expansionMinScore,
        requestBudget: expansionRequestBudget,
        sessionBudget: scopeKey ? expansionSessionBudget : undefined,
        sessionRemaining: scopeKey ? remainingSessionBudget : undefined,
        generatedQueries: [],
        executedQueries: [],
        skippedQueries,
      };
    }
  }

  if (options?.adaptive !== false) {
    const existingSites = normalizeCsvLikeList(request.operators?.site).map(
      normalizeSiteHost,
    );
    const adaptiveSites = extractAdaptiveSitesFromResults(
      result.items,
      existingSites,
    );
    const adaptiveQueries = buildAdaptiveUsernameQueries({
      username: result.meta.query,
      sites: adaptiveSites,
    }).slice(0, MAX_ADAPTIVE_SWEEP_QUERIES);

    if (adaptiveQueries.length > 0) {
      result.followUpQueries = await Promise.all(
        adaptiveQueries.map(async (adaptiveQuery) => {
          const followUpInput: StructuredQueryInput = {
            ...input,
            site: adaptiveQuery.site,
          };
          const followUpResponse = await runStructuredQuery(
            followUpInput,
            {
              num: options?.num ?? DEFAULT_BATCH_PAGE_SIZE,
              cache: options?.cache,
              adaptive: false,
              serpApiContext,
              expansionRounds: 0,
            },
          );

          return {
            site: adaptiveQuery.site,
            query: buildSearchQuery({
              operators: {
                site: followUpInput.site,
                inurl: followUpInput.inurl,
                intitle: followUpInput.intitle,
                intext: followUpInput.intext,
                filetype: followUpInput.filetype,
                before: followUpInput.before,
                after: followUpInput.after,
              },
              freeText: followUpInput.freeText,
            }),
            results: followUpResponse.items,
            totalResults: followUpResponse.meta.totalResults,
          };
        })
      );
    }
  }

  if (shouldUseCache) {
    await setCache(cacheKey, result as unknown as JsonRecord);
  }

  await persistHistory(
    "structured-query",
    "Structured query",
    result.meta.query,
    result as unknown as JsonRecord,
  );

  return result;
}

export async function runBatchDiscovery(
  request: BatchDiscoveryRequest,
): Promise<BatchDiscoveryResponse> {
  const target = normalizeTarget(request.target);
  const requestedExtensions = normalizeCsvLikeList(request.extensions).map(
    (item) => item.replace(/^\./, "").toLowerCase(),
  );

  const baseExtensions =
    requestedExtensions.length > 0
      ? requestedExtensions
      : [...ALL_DISCOVERY_FILE_TYPES];

  const extensions = baseExtensions.filter((extension) => {
    const meta = FILE_FORMAT_LOOKUP[extension];

    if (!meta) {
      return false;
    }

    if (meta.group === "config" && request.includeConfigFormats === false) {
      return false;
    }

    if (meta.group === "archive" && request.includeArchiveFormats === false) {
      return false;
    }

    return true;
  });

  const queries = buildBatchQueries({
    seed: target,
    filetypes: extensions,
  });

  const cacheKey = buildCacheKey("search:batch", {
    target,
    extensions,
    maxResultsPerQuery: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
  });

  const cached = await getCache<BatchDiscoveryResponse>(cacheKey);
  if (cached) {
    return {
      ...cached,
      cached: true,
      progress: {
        ...cached.progress,
        status: "complete",
      },
    };
  }

  // SerpAPI is intentionally restricted to structured build-query and target-sweep flows.
  const restrictedResponse: BatchDiscoveryResponse = {
    target,
    progress: {
      completed: queries.length,
      total: queries.length,
      status: "complete",
    },
    findings: [],
    executedQueries: queries.map((item) => item.query),
    cached: false,
    serpApiRestricted: true,
    serpApiRestrictionReason:
      "SerpAPI is restricted to BuildQuery and TargetSweep(name,email,username).",
    generatedAt: nowIso(),
  };

  await setCache(cacheKey, restrictedResponse as unknown as JsonRecord);
  await persistHistory(
    "batch-discovery",
    "Batch discovery",
    target,
    restrictedResponse as unknown as JsonRecord,
    target,
    extensions,
  );

  return restrictedResponse;
}

export async function analyzeImagePipeline(
  request: ImageAnalysisRequest,
): Promise<ImageAnalysisResponse> {
  const cacheKey = buildCacheKey("image:analyze", {
    sourceType: request.sourceType,
    imageUrl: request.imageUrl,
    filename: request.filename,
    imageBase64Hash: request.imageBase64
      ? `${request.imageBase64.length}:${request.imageBase64.slice(0, 32)}`
      : undefined,
  });

  const cached = await getCache<ImageAnalysisResponse>(cacheKey);
  if (cached) {
    return cached;
  }

  const image =
    request.sourceType === "url" && request.imageUrl
      ? await loadImage({ type: "url", value: request.imageUrl })
      : request.imageBase64
        ? await loadImage({ type: "base64", value: request.imageBase64 })
        : null;

  if (!image) {
    throw new Error(
      "Image analysis requires either a valid image URL or base64 payload.",
    );
  }

  const ocrStart = Date.now();
  const ocr = await extractTextWithOcr(image);

  const ocrResult = {
    rawText: ocr.text,
    blocks: ocr.lines.map((line) => ({
      text: line,
      confidence: ocr.confidence,
    })),
    durationMs: Date.now() - ocrStart,
  };

  const hasVision = featureAvailability.vision;
  let visionRaw = visionFallbackFromOcr(ocr.lines);

  if (hasVision) {
    try {
      visionRaw = await runGeminiVision(image, ocr.lines);
    } catch (error) {
      console.error("Gemini vision analysis failed. Falling back to OCR-only mode.", error);
      visionRaw = {
        ...visionFallbackFromOcr(ocr.lines),
        summary:
          "Gemini vision call failed. OCR-only fallback mode completed.",
      };
    }
  }

  const identifiers: ExtractedIdentifier[] = visionRaw.entities.map(
    (entity) => ({
      type: toIdentifierType(entity.type),
      value: entity.value,
      confidence: entity.confidence,
      context: entity.notes || entity.sourceText,
    }),
  );

  const generatedQueryStrings = Array.from(
    new Set([
      ...visionRaw.suggestedQueries,
      ...buildQueriesFromIdentifiers(identifiers.map((item) => item.value)),
    ]),
  ).slice(0, 12);

  const generatedQueries: AutoGeneratedQuery[] = generatedQueryStrings.map(
    (query) => {
      const matched = identifiers.find((item) => query.includes(item.value));

      return {
        identifier: matched?.value ?? query,
        identifierType: matched?.type ?? "other",
        query,
      };
    },
  );

  let relatedResults: SearchQueryResponse[] | undefined = undefined;

  const allowImageRelatedSerpApi = false;

  if (allowImageRelatedSerpApi && featureAvailability.googleSearch && generatedQueries.length > 0) {
    relatedResults = await Promise.all(
      generatedQueries.slice(0, MAX_RELATED_IMAGE_QUERIES).map((entry) =>
        runStructuredQuery(
          {
            freeText: entry.query,
          },
          { num: DEFAULT_BATCH_PAGE_SIZE, serpApiContext: "image-analysis" },
        ),
      ),
    );
  }

  const result: ImageAnalysisResponse = {
    sourceType: request.sourceType,
    ocr: ocrResult,
    vision: {
      summary: visionRaw.summary,
      identifiers,
      raw:
        typeof visionRaw.raw === "object" &&
          visionRaw.raw !== null
          ? (visionRaw.raw as Record<string, unknown>)
          : undefined,
      model: hasVision ? "gemini-2.5-flash" : undefined,
    },
    generatedQueries,
    relatedResults,
    serpApiRestricted: !allowImageRelatedSerpApi,
    serpApiRestrictionReason: !allowImageRelatedSerpApi
      ? "SerpAPI is restricted to BuildQuery and TargetSweep(name,email,username)."
      : undefined,
    generatedAt: nowIso(),
  };

  await setCache(cacheKey, result as unknown as JsonRecord);
  await persistHistory(
    "image-analysis",
    "Image analysis",
    request.imageUrl ?? request.filename ?? "uploaded-image",
    result as unknown as JsonRecord,
    request.imageUrl ?? request.filename,
    ["ocr", hasVision ? "vision" : "ocr-only"],
  );

  return result;
}

function buildSweepSectionsFromMap(
  queryMap: Record<string, string>,
  results: Record<string, SearchQueryResponse>,
): SweepSection[] {
  const descriptors: Record<string, { label: string; description: string }> = {
    usernamePresence: {
      label: "Username Presence",
      description:
        "Cross-platform public profile discovery for the supplied handle.",
    },
    emailDocuments: {
      label: "Email in Documents",
      description: "Public document search for the supplied email address.",
    },
    nameDocuments: {
      label: "Name in Documents",
      description: "Public filetype discovery for the supplied personal name.",
    },
    domainDiscovery: {
      label: "Domain Document Discovery",
      description: "Domain-focused public document and artifact discovery.",
    },
    webMentions: {
      label: "General Web Mentions",
      description: "Broad site scan across all indexed pages and text.",
    },
  };

  return Object.entries(queryMap)
    .filter(([, query]) => Boolean(normalizeWhitespace(query)))
    .map(([id, query]) => {
      const response = results[id];
      const descriptor = descriptors[id] ?? {
        label: id,
        description: "Coordinated search section.",
      };

      return {
        id,
        label: descriptor.label,
        description: descriptor.description,
        query,
        results: response?.items ?? [],
        totalResults: response?.meta.totalResults ?? 0,
      };
    });
}

export async function runTargetSweep(
  request: TargetSweepRequest,
): Promise<TargetSweepResponse> {
  const target = normalizeTarget(request.target);
  const type = request.type ?? inferSweepType(target);

  // Domain sweeps use dedicated OSINT sources and avoid SerpAPI-backed web queries.
  if (type === "domain") {
    const domainOnlyResult: TargetSweepResponse = {
      target,
      type,
      sections: [],
      cached: false,
      generatedAt: nowIso(),
    };

    await persistHistory(
      "target-sweep",
      "Target sweep",
      target,
      domainOnlyResult as unknown as JsonRecord,
      target,
      [type],
    );

    return domainOnlyResult;
  }

  const queryMap = buildTargetSweepQueries({
    name: type === "name" ? target : undefined,
    email: type === "email" ? target : undefined,
    username: type === "username" ? target : undefined,
    domain: undefined,
  });

  const cacheKey = buildCacheKey("target:sweep", {
    target,
    type,
    maxResultsPerQuery: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
  });

  const cached = await getCache<TargetSweepResponse>(cacheKey);
  if (cached) {
    return {
      ...cached,
      cached: true,
    };
  }

  const queryEntries = Object.entries(queryMap).filter(([, query]) =>
    Boolean(normalizeWhitespace(query)),
  );

  const resultsMap: Record<string, SearchQueryResponse> = {};

  const queryPromises = queryEntries.map(async ([key, query]) => {
    const response = await runStructuredQuery(
      { freeText: query },
        {
          num: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
          serpApiContext: "target-sweep",
        },
    );
    return { key, response };
  });

  const queryResults = await Promise.all(queryPromises);
  
  for (const { key, response } of queryResults) {
    resultsMap[key] = response;
  }

  const adaptiveSections: SweepSection[] = [];

  if (type === "username") {
    const adaptiveSites = extractAdaptiveSitesFromResults(
      [
        ...(resultsMap.usernamePresence?.items ?? []),
        ...(resultsMap.webMentions?.items ?? []),
      ],
      [...USERNAME_PRESENCE_SITES],
    );
    const adaptiveQueries = buildAdaptiveUsernameQueries({
      username: target,
      sites: adaptiveSites,
    }).slice(0, MAX_ADAPTIVE_SWEEP_QUERIES);

    const adaptiveSectionsResults = await Promise.all(
      adaptiveQueries.map(async (adaptiveQuery) => {
        const response = await runStructuredQuery(
          {
            freeText: target,
            site: adaptiveQuery.site,
          },
          {
            num: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
            serpApiContext: "target-sweep",
          },
        );

        return {
          id: `adaptive-site:${adaptiveQuery.site}`,
          label: `Adaptive Site Pivot // ${adaptiveQuery.site}`,
          description:
            "Auto-generated follow-up query added from newly surfaced username results.",
          query: adaptiveQuery.query,
          results: response.items,
          totalResults: response.meta.totalResults,
        };
      })
    );

    adaptiveSections.push(...adaptiveSectionsResults);
  }

  const result: TargetSweepResponse = {
    target,
    type,
    sections: [
      ...buildSweepSectionsFromMap(queryMap, resultsMap),
      ...adaptiveSections,
    ],
    cached: false,
    generatedAt: nowIso(),
  };

  await setCache(cacheKey, result as unknown as JsonRecord);
  await persistHistory(
    "target-sweep",
    "Target sweep",
    target,
    result as unknown as JsonRecord,
    target,
    [type],
  );

  return result;
}

export async function replayQueries(
  queries: string[],
  options?: { limit?: number },
) {
  const unique = Array.from(
    new Set(queries.map((query) => normalizeWhitespace(query)).filter(Boolean)),
  ).slice(0, options?.limit ?? 10);

  const responses = await Promise.all(
    unique.map((query) =>
      runStructuredQuery(
        {
          freeText: query,
        },
        { num: DEFAULT_BATCH_PAGE_SIZE },
      ),
    ),
  );

  return responses;
}

export async function generateImagePivotQueries(
  identifiers: string[],
  options?: { site?: string; filetype?: string },
) {
  return buildQueriesFromIdentifiers(identifiers, options).map((query) => ({
    query,
  }));
}
