import {
  appendHistory,
  buildCacheKey,
  getCache,
  getCacheTtlSeconds,
  setCache,
} from "@/lib/cache";
import { FILE_FORMAT_LOOKUP } from "@/lib/data/presets";
import { featureAvailability } from "@/lib/env";
import { searchGoogleCse, type GoogleCseRequest } from "@/lib/api/google-cse";

import { extractTextWithOcr, loadImage } from "@/lib/image";
import {
  ALL_DISCOVERY_FILE_TYPES,
  buildAdaptiveUsernameQueries,
  buildBatchQueries,
  buildQueriesFromIdentifiers,
  buildSearchQuery,
  buildTargetSweepQueries,
  USERNAME_PRESENCE_SITES,
} from "@/lib/query";
import type {
  AutoGeneratedQuery,
  BatchDiscoveryFinding,
  BatchDiscoveryRequest,
  BatchDiscoveryResponse,
  ExtractedIdentifier,
  ImageAnalysisRequest,
  ImageAnalysisResponse,
  SearchQueryResponse,
  SearchResultItem,
  StructuredQueryInput,
  SweepSection,
  SweepTargetType,
  TargetSweepRequest,
  TargetSweepResponse,
} from "@/lib/types/osint";

type HistoryKind =
  | "structured-query"
  | "batch-discovery"
  | "image-analysis"
  | "target-sweep";

type JsonRecord = Record<string, unknown>;

const DEFAULT_SEARCH_PAGE_SIZE = 10;
const DEFAULT_BATCH_PAGE_SIZE = 5;
const MAX_RELATED_IMAGE_QUERIES = 4;
const MAX_ADAPTIVE_SWEEP_QUERIES = 6;

function nowIso() {
  return new Date().toISOString();
}

function normalizeWhitespace(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function normalizeCsvLikeList(value?: string | string[]) {
  if (!value) {
    return [];
  }

  const list = Array.isArray(value) ? value : value.split(/[,\n]/g);

  return Array.from(
    new Set(list.map((item) => normalizeWhitespace(item)).filter(Boolean)),
  );
}

function normalizeTarget(value: string) {
  return normalizeWhitespace(value);
}

function isDomainLike(value: string) {
  return /^[a-z0-9.-]+\.[a-z]{2,}$/i.test(value.trim());
}

function inferSweepType(target: string): SweepTargetType {
  const value = target.trim();

  if (value.includes("@")) {
    return "email";
  }

  if (isDomainLike(value)) {
    return "domain";
  }

  if (/^[a-z0-9._-]{3,}$/i.test(value) && !/\s/.test(value)) {
    return "username";
  }

  return "name";
}

function safeNumber(value: unknown, fallback = 0) {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }

  return fallback;
}

function mapSearchResultItem(item: {
  title?: string;
  link?: string;
  snippet?: string;
  displayLink?: string;
  formattedUrl?: string;
  mime?: string;
  fileFormat?: string;
}): SearchResultItem {
  const rawLink = typeof item.link === "string" ? item.link : "";

  return {
    title: typeof item.title === "string" ? item.title : "Untitled result",
    link: rawLink,
    snippet: typeof item.snippet === "string" ? item.snippet : "",
    displayLink:
      typeof item.displayLink === "string" ? item.displayLink : undefined,
    formattedUrl:
      typeof item.formattedUrl === "string" ? item.formattedUrl : undefined,
    mime: typeof item.mime === "string" ? item.mime : undefined,
    fileFormat:
      typeof item.fileFormat === "string" ? item.fileFormat : undefined,
    filetype: inferFiletypeFromResult({
      link: rawLink,
      fileFormat:
        typeof item.fileFormat === "string" ? item.fileFormat : undefined,
      mime: typeof item.mime === "string" ? item.mime : undefined,
    }),
  };
}

function inferFiletypeFromResult(input: {
  link?: string;
  mime?: string;
  fileFormat?: string;
}) {
  const link = input.link?.toLowerCase() ?? "";

  const byLink = link.match(/\.([a-z0-9]{2,8})(?:$|[?#])/i)?.[1];
  if (byLink) {
    return byLink;
  }

  const fileFormat = input.fileFormat?.toLowerCase() ?? "";
  const byFormat = fileFormat.match(
    /\b(pdf|docx|xlsx|pptx|txt|csv|json|yaml|xml|sql|log|env|zip|tar)\b/i,
  )?.[1];
  if (byFormat) {
    return byFormat.toLowerCase();
  }

  const mime = input.mime?.toLowerCase() ?? "";
  if (mime.includes("pdf")) return "pdf";
  if (mime.includes("json")) return "json";
  if (mime.includes("xml")) return "xml";
  if (mime.includes("zip")) return "zip";
  if (mime.includes("text/plain")) return "txt";

  return undefined;
}

function toIdentifierType(type: string): ExtractedIdentifier["type"] {
  switch (type) {
    case "name":
    case "username":
    case "email":
    case "domain":
    case "phone":
    case "organization":
      return type;
    default:
      return "other";
  }
}

function dedupeResults(items: SearchResultItem[]) {
  const seen = new Set<string>();

  return items.filter((item) => {
    const key = item.link || `${item.title}:${item.snippet}`;
    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

function dedupeFindings(items: BatchDiscoveryFinding[]) {
  const seen = new Set<string>();

  return items.filter((item) => {
    const key = `${item.extension}:${item.link}`;
    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

function normalizeSiteHost(value: string) {
  return value.replace(/^www\./i, "").trim().toLowerCase();
}

function extractHostname(value?: string) {
  if (!value) {
    return null;
  }

  try {
    return normalizeSiteHost(new URL(value).hostname);
  } catch {
    return null;
  }
}

function extractAdaptiveSitesFromResults(
  items: SearchResultItem[],
  excludedSites: string[],
) {
  const excluded = new Set(excludedSites.map(normalizeSiteHost));

  return Array.from(
    new Set(
      items
        .flatMap((item) => [
          extractHostname(item.link),
          item.displayLink ? normalizeSiteHost(item.displayLink) : null,
        ])
        .filter((site): site is string => Boolean(site && site.includes(".")))
        .filter((site) => !excluded.has(site)),
    ),
  );
}

function toStructuredRequest(
  input: StructuredQueryInput,
  start = 1,
  num = DEFAULT_SEARCH_PAGE_SIZE,
): GoogleCseRequest {
  return {
    query: normalizeWhitespace(input.freeText ?? ""),
    operators: {
      site: normalizeCsvLikeList(input.site),
      inurl: normalizeCsvLikeList(input.inurl),
      intitle: normalizeCsvLikeList(input.intitle),
      intext: normalizeCsvLikeList(input.intext),
      filetype: normalizeCsvLikeList(input.filetype),
      before: normalizeCsvLikeList(input.before),
      after: normalizeCsvLikeList(input.after),
    },
    exactTerms: normalizeCsvLikeList(input.exactTerms),
    excludeTerms: normalizeCsvLikeList(input.excludeTerms),
    start,
    num,
  };
}

export async function persistHistory(
  kind: HistoryKind,
  title: string,
  query: string,
  payload: JsonRecord,
  target?: string,
  tags?: string[],
) {
  await appendHistory({
    type: kind,
    title,
    query,
    target,
    tags,
    ttlSeconds: getCacheTtlSeconds(),
    payload,
  });
}

export async function runStructuredQuery(
  input: StructuredQueryInput,
  options?: {
    start?: number;
    num?: number;
    cache?: boolean;
    adaptive?: boolean;
  },
): Promise<SearchQueryResponse> {
  const request = toStructuredRequest(
    input,
    options?.start ?? 1,
    options?.num ?? DEFAULT_SEARCH_PAGE_SIZE,
  );

  const query = buildSearchQuery({
    operators: {
      site: request.operators?.site,
      inurl: request.operators?.inurl,
      intitle: request.operators?.intitle,
      intext: request.operators?.intext,
      filetype: request.operators?.filetype,
      before: request.operators?.before,
      after: request.operators?.after,
    },
    freeText: request.query,
  });

  const cacheKey = buildCacheKey("search:query", {
    request,
    query,
  });

  if (options?.cache !== false) {
    const cached = await getCache<SearchQueryResponse>(cacheKey);
    if (cached) {
      return {
        ...cached,
        meta: {
          ...cached.meta,
          cached: true,
          source: cached.meta.source === "mock" ? "mock" : "cache",
          cacheKey,
        },
      };
    }
  }

  if (!query) {
    return {
      meta: {
        query: "",
        totalResults: 0,
        startIndex: request.start ?? 1,
        count: request.num ?? DEFAULT_SEARCH_PAGE_SIZE,
        cached: false,
        cacheKey,
        source: "mock",
        generatedAt: nowIso(),
      },
      items: [],
    };
  }

  if (!featureAvailability.googleSearch) {
    const mockResponse: SearchQueryResponse = {
      meta: {
        query,
        totalResults: 0,
        startIndex: request.start ?? 1,
        count: request.num ?? DEFAULT_SEARCH_PAGE_SIZE,
        cached: false,
        cacheKey,
        source: "mock",
        generatedAt: nowIso(),
      },
      items: [],
    };

    if (options?.cache !== false) {
      await setCache(cacheKey, mockResponse as unknown as JsonRecord);
    }

    await persistHistory(
      "structured-query",
      "Structured query",
      query,
      mockResponse as unknown as JsonRecord,
    );

    return mockResponse;
  }

  const response = await searchGoogleCse(request);

  const result: SearchQueryResponse = {
    meta: {
      query: response.searchTerms || query,
      totalResults: safeNumber(response.totalResults),
      startIndex: safeNumber(response.startIndex, 1),
      count: safeNumber(response.count, DEFAULT_SEARCH_PAGE_SIZE),
      searchTime: safeNumber(response.searchTime),
      cached: false,
      cacheKey,
      source: "google",
      generatedAt: nowIso(),
    },
    items: dedupeResults(response.items.map(mapSearchResultItem)),
  };

  if (options?.adaptive !== false) {
    const existingSites = normalizeCsvLikeList(request.operators?.site).map(
      normalizeSiteHost,
    );
    const adaptiveSites = extractAdaptiveSitesFromResults(
      result.items,
      existingSites,
    );
    const adaptiveQueries = buildAdaptiveUsernameQueries({
      username: result.meta.query,
      sites: adaptiveSites,
    }).slice(0, MAX_ADAPTIVE_SWEEP_QUERIES);

    if (adaptiveQueries.length > 0) {
      result.followUpQueries = await Promise.all(
        adaptiveQueries.map(async (adaptiveQuery) => {
          const followUpInput: StructuredQueryInput = {
            ...input,
            site: adaptiveQuery.site,
          };
          const followUpResponse = await runStructuredQuery(
            followUpInput,
            {
              num: options?.num ?? DEFAULT_BATCH_PAGE_SIZE,
              cache: options?.cache,
              adaptive: false,
            },
          );

          return {
            site: adaptiveQuery.site,
            query: buildSearchQuery({
              operators: {
                site: followUpInput.site,
                inurl: followUpInput.inurl,
                intitle: followUpInput.intitle,
                intext: followUpInput.intext,
                filetype: followUpInput.filetype,
                before: followUpInput.before,
                after: followUpInput.after,
              },
              freeText: followUpInput.freeText,
            }),
            results: followUpResponse.items,
            totalResults: followUpResponse.meta.totalResults,
          };
        })
      );
    }
  }

  if (options?.cache !== false) {
    await setCache(cacheKey, result as unknown as JsonRecord);
  }

  await persistHistory(
    "structured-query",
    "Structured query",
    result.meta.query,
    result as unknown as JsonRecord,
  );

  return result;
}

export async function runBatchDiscovery(
  request: BatchDiscoveryRequest,
): Promise<BatchDiscoveryResponse> {
  const target = normalizeTarget(request.target);
  const requestedExtensions = normalizeCsvLikeList(request.extensions).map(
    (item) => item.replace(/^\./, "").toLowerCase(),
  );

  const baseExtensions =
    requestedExtensions.length > 0
      ? requestedExtensions
      : [...ALL_DISCOVERY_FILE_TYPES];

  const extensions = baseExtensions.filter((extension) => {
    const meta = FILE_FORMAT_LOOKUP[extension];

    if (!meta) {
      return false;
    }

    if (meta.group === "config" && request.includeConfigFormats === false) {
      return false;
    }

    if (meta.group === "archive" && request.includeArchiveFormats === false) {
      return false;
    }

    return true;
  });

  const queries = buildBatchQueries({
    seed: target,
    filetypes: extensions,
  });

  const cacheKey = buildCacheKey("search:batch", {
    target,
    extensions,
    maxResultsPerQuery: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
  });

  const cached = await getCache<BatchDiscoveryResponse>(cacheKey);
  if (cached) {
    return {
      ...cached,
      cached: true,
      progress: {
        ...cached.progress,
        status: "complete",
      },
    };
  }

  const findings: BatchDiscoveryFinding[] = [];

  if (!featureAvailability.googleSearch) {
    const mockResponse: BatchDiscoveryResponse = {
      target,
      progress: {
        completed: queries.length,
        total: queries.length,
        status: "complete",
      },
      findings: [],
      executedQueries: queries.map((item) => item.query),
      cached: false,
      generatedAt: nowIso(),
    };

    await setCache(cacheKey, mockResponse as unknown as JsonRecord);
    await persistHistory(
      "batch-discovery",
      "Batch discovery",
      target,
      mockResponse as unknown as JsonRecord,
      target,
      extensions,
    );

    return mockResponse;
  }

  const batchResults = await Promise.all(
    queries.map(async (batchQuery) => {
      const response = await searchGoogleCse({
        query: batchQuery.query,
        start: 1,
        num: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
      });

      const formatMeta = FILE_FORMAT_LOOKUP[batchQuery.filetype];

      return response.items.map((item) => ({
        ...mapSearchResultItem(item),
        extension: batchQuery.filetype,
        category: formatMeta?.group ?? "other",
        query: batchQuery.query,
      }));
    })
  );

  findings.push(...batchResults.flat());

  const result: BatchDiscoveryResponse = {
    target,
    progress: {
      completed: queries.length,
      total: queries.length,
      status: "complete",
    },
    findings: dedupeFindings(findings),
    executedQueries: queries.map((item) => item.query),
    cached: false,
    generatedAt: nowIso(),
  };

  await setCache(cacheKey, result as unknown as JsonRecord);
  
  if (!request.skipHistory) {
    await persistHistory(
      "batch-discovery",
      "Batch discovery",
      target,
      result as unknown as JsonRecord,
      target,
      extensions,
    );
  }

  return result;
}

export async function analyzeImagePipeline(
  request: ImageAnalysisRequest,
): Promise<ImageAnalysisResponse> {
  const cacheKey = buildCacheKey("image:analyze", {
    sourceType: request.sourceType,
    imageUrl: request.imageUrl,
    filename: request.filename,
    imageBase64Hash: request.imageBase64
      ? `${request.imageBase64.length}:${request.imageBase64.slice(0, 32)}`
      : undefined,
  });

  const cached = await getCache<ImageAnalysisResponse>(cacheKey);
  if (cached) {
    return cached;
  }

  const image =
    request.sourceType === "url" && request.imageUrl
      ? await loadImage({ type: "url", value: request.imageUrl })
      : request.imageBase64
        ? await loadImage({ type: "base64", value: request.imageBase64 })
        : null;

  if (!image) {
    throw new Error(
      "Image analysis requires either a valid image URL or base64 payload.",
    );
  }

  const ocrStart = Date.now();
  const ocr = await extractTextWithOcr(image);

  const ocrResult = {
    rawText: ocr.text,
    blocks: ocr.lines.map((line) => ({
      text: line,
      confidence: ocr.confidence,
    })),
    durationMs: Date.now() - ocrStart,
  };

  const hasVision = false;

  const visionRaw: {
    summary: string;
    entities: { type: string; value: string; confidence: number; notes?: string; sourceText: string }[];
    suggestedQueries: string[];
    notableText: string[];
    raw?: unknown;
  } = {
    summary: "Gemini vision is not configured. OCR-only mode completed.",
    entities: [],
    suggestedQueries: buildQueriesFromIdentifiers(
      normalizeCsvLikeList(ocr.lines).slice(0, 8),
    ),
    notableText: ocr.lines.slice(0, 12),
  };

  const identifiers: ExtractedIdentifier[] = visionRaw.entities.map(
    (entity) => ({
      type: toIdentifierType(entity.type),
      value: entity.value,
      confidence: entity.confidence,
      context: entity.notes || entity.sourceText,
    }),
  );

  const generatedQueryStrings = Array.from(
    new Set([
      ...visionRaw.suggestedQueries,
      ...buildQueriesFromIdentifiers(identifiers.map((item) => item.value)),
    ]),
  ).slice(0, 12);

  const generatedQueries: AutoGeneratedQuery[] = generatedQueryStrings.map(
    (query) => {
      const matched = identifiers.find((item) => query.includes(item.value));

      return {
        identifier: matched?.value ?? query,
        identifierType: matched?.type ?? "other",
        query,
      };
    },
  );

  let relatedResults: SearchQueryResponse[] | undefined = undefined;

  if (featureAvailability.googleSearch && generatedQueries.length > 0) {
    relatedResults = await Promise.all(
      generatedQueries.slice(0, MAX_RELATED_IMAGE_QUERIES).map((entry) =>
        runStructuredQuery(
          {
            freeText: entry.query,
          },
          { num: DEFAULT_BATCH_PAGE_SIZE },
        ),
      ),
    );
  }

  const result: ImageAnalysisResponse = {
    sourceType: request.sourceType,
    ocr: ocrResult,
    vision: {
      summary: visionRaw.summary,
      identifiers,
      raw:
        typeof (visionRaw as any).raw === "object" &&
          (visionRaw as any).raw !== null
          ? ((visionRaw as any).raw as Record<string, unknown>)
          : undefined,
      model: hasVision ? "gemini-2.0-flash" : undefined,
    },
    generatedQueries,
    relatedResults,
    generatedAt: nowIso(),
  };

  await setCache(cacheKey, result as unknown as JsonRecord);
  await persistHistory(
    "image-analysis",
    "Image analysis",
    request.imageUrl ?? request.filename ?? "uploaded-image",
    result as unknown as JsonRecord,
    request.imageUrl ?? request.filename,
    ["ocr", hasVision ? "vision" : "ocr-only"],
  );

  return result;
}

function buildSweepSectionsFromMap(
  queryMap: Record<string, string>,
  results: Record<string, SearchQueryResponse>,
): SweepSection[] {
  const descriptors: Record<string, { label: string; description: string }> = {
    usernamePresence: {
      label: "Username Presence",
      description:
        "Cross-platform public profile discovery for the supplied handle.",
    },
    emailDocuments: {
      label: "Email in Documents",
      description: "Public document search for the supplied email address.",
    },
    nameDocuments: {
      label: "Name in Documents",
      description: "Public filetype discovery for the supplied personal name.",
    },
    domainDiscovery: {
      label: "Domain Document Discovery",
      description: "Domain-focused public document and artifact discovery.",
    },
    webMentions: {
      label: "General Web Mentions",
      description: "Broad site scan across all indexed pages and text.",
    },
  };

  return Object.entries(queryMap)
    .filter(([, query]) => Boolean(normalizeWhitespace(query)))
    .map(([id, query]) => {
      const response = results[id];
      const descriptor = descriptors[id] ?? {
        label: id,
        description: "Coordinated search section.",
      };

      return {
        id,
        label: descriptor.label,
        description: descriptor.description,
        query,
        results: response?.items ?? [],
        totalResults: response?.meta.totalResults ?? 0,
      };
    });
}

export async function runTargetSweep(
  request: TargetSweepRequest,
): Promise<TargetSweepResponse> {
  const target = normalizeTarget(request.target);
  const type = request.type ?? inferSweepType(target);

  const queryMap = buildTargetSweepQueries({
    name: type === "name" ? target : undefined,
    email: type === "email" ? target : undefined,
    username: type === "username" ? target : undefined,
    domain: type === "domain" ? target : undefined,
  });

  const cacheKey = buildCacheKey("target:sweep", {
    target,
    type,
    maxResultsPerQuery: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
  });

  const cached = await getCache<TargetSweepResponse>(cacheKey);
  if (cached) {
    return {
      ...cached,
      cached: true,
    };
  }

  const queryEntries = Object.entries(queryMap).filter(([, query]) =>
    Boolean(normalizeWhitespace(query)),
  );

  const resultsMap: Record<string, SearchQueryResponse> = {};

  const queryPromises = queryEntries.map(async ([key, query]) => {
    const response = await runStructuredQuery(
      { freeText: query },
      { num: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE }
    );
    return { key, response };
  });

  const queryResults = await Promise.all(queryPromises);
  
  for (const { key, response } of queryResults) {
    resultsMap[key] = response;
  }

  const adaptiveSections: SweepSection[] = [];

  if (type === "username") {
    const adaptiveSites = extractAdaptiveSitesFromResults(
      [
        ...(resultsMap.usernamePresence?.items ?? []),
        ...(resultsMap.webMentions?.items ?? []),
      ],
      [...USERNAME_PRESENCE_SITES],
    );
    const adaptiveQueries = buildAdaptiveUsernameQueries({
      username: target,
      sites: adaptiveSites,
    }).slice(0, MAX_ADAPTIVE_SWEEP_QUERIES);

    const adaptiveSectionsResults = await Promise.all(
      adaptiveQueries.map(async (adaptiveQuery) => {
        const response = await runStructuredQuery(
          {
            freeText: target,
            site: adaptiveQuery.site,
          },
          {
            num: request.maxResultsPerQuery ?? DEFAULT_BATCH_PAGE_SIZE,
          },
        );

        return {
          id: `adaptive-site:${adaptiveQuery.site}`,
          label: `Adaptive Site Pivot // ${adaptiveQuery.site}`,
          description:
            "Auto-generated follow-up query added from newly surfaced username results.",
          query: adaptiveQuery.query,
          results: response.items,
          totalResults: response.meta.totalResults,
        };
      })
    );

    adaptiveSections.push(...adaptiveSectionsResults);
  }

  const result: TargetSweepResponse = {
    target,
    type,
    sections: [
      ...buildSweepSectionsFromMap(queryMap, resultsMap),
      ...adaptiveSections,
    ],
    cached: false,
    generatedAt: nowIso(),
  };

  await setCache(cacheKey, result as unknown as JsonRecord);
  await persistHistory(
    "target-sweep",
    "Target sweep",
    target,
    result as unknown as JsonRecord,
    target,
    [type],
  );

  return result;
}

export async function replayQueries(
  queries: string[],
  options?: { limit?: number },
) {
  const unique = Array.from(
    new Set(queries.map((query) => normalizeWhitespace(query)).filter(Boolean)),
  ).slice(0, options?.limit ?? 10);

  const responses = await Promise.all(
    unique.map((query) =>
      runStructuredQuery(
        {
          freeText: query,
        },
        { num: DEFAULT_BATCH_PAGE_SIZE },
      ),
    ),
  );

  return responses;
}

export async function generateImagePivotQueries(
  identifiers: string[],
  options?: { site?: string; filetype?: string },
) {
  return buildQueriesFromIdentifiers(identifiers, options).map((query) => ({
    query,
  }));
}
