export type SearchOperator =
  | "site"
  | "inurl"
  | "intitle"
  | "intext"
  | "filetype"
  | "before"
  | "after";

export type ResearchTab =
  | "query-builder"
  | "document-scan"
  | "image-ai"
  | "target-sweep";

export type SearchPresetCategory =
  | "exposed-config"
  | "open-directories"
  | "public-documents"
  | "social-enumeration";

export type FileCategory = "document" | "config" | "archive" | "other";

export type ExportFormat = "json" | "csv" | "pdf";

export type SweepTargetType = "name" | "email" | "username" | "domain";

export type ImageSourceType = "upload" | "url";

export interface StructuredQueryInput {
  site?: string;
  inurl?: string;
  intitle?: string;
  intext?: string;
  filetype?: string;
  before?: string;
  after?: string;
  freeText?: string;
  exactTerms?: string[];
  excludeTerms?: string[];
}

export interface SearchPreset {
  id: string;
  label: string;
  description: string;
  category: SearchPresetCategory;
  template: StructuredQueryInput;
  tags: string[];
}

export interface SearchResultItem {
  title: string;
  link: string;
  snippet: string;
  displayLink?: string;
  formattedUrl?: string;
  mime?: string;
  fileFormat?: string;
  filetype?: string;
  cacheId?: string;
  pagemap?: Record<string, unknown>;
}

export interface SearchResponseMeta {
  query: string;
  totalResults: number;
  startIndex: number;
  count: number;
  searchTime?: number;
  cached: boolean;
  cacheKey?: string;
  source: "google" | "cache" | "mock";
  generatedAt: string;
}

export interface AdaptiveQueryResult {
  site: string;
  query: string;
  results: SearchResultItem[];
  totalResults: number;
}

export interface SearchQueryResponse {
  meta: SearchResponseMeta;
  items: SearchResultItem[];
  followUpQueries?: AdaptiveQueryResult[];
  aiExpansion?: {
    rounds: number;
    minScore: number;
    requestBudget: number;
    sessionBudget?: number;
    sessionRemaining?: number;
    generatedQueries: string[];
    executedQueries: AdaptiveQueryResult[];
    skippedQueries?: Array<{
      query: string;
      score?: number;
      reason: string;
    }>;
  };
}

export interface FiletypeDiscoveryGroup {
  category: FileCategory;
  extensions: string[];
}

export interface BatchDiscoveryRequest {
  target: string;
  includeConfigFormats?: boolean;
  includeArchiveFormats?: boolean;
  extensions?: string[];
  maxResultsPerQuery?: number;
  skipHistory?: boolean;
}

export interface BatchDiscoveryProgress {
  completed: number;
  total: number;
  activeExtension?: string;
  status: "idle" | "running" | "complete" | "error";
}

export interface BatchDiscoveryFinding extends SearchResultItem {
  extension: string;
  category: FileCategory;
  query: string;
}

export interface BatchDiscoveryResponse {
  target: string;
  progress: BatchDiscoveryProgress;
  findings: BatchDiscoveryFinding[];
  executedQueries: string[];
  cached: boolean;
  serpApiRestricted?: boolean;
  serpApiRestrictionReason?: string;
  generatedAt: string;
}

export interface OcrBlock {
  text: string;
  confidence?: number;
  bbox?: {
    x0: number;
    y0: number;
    x1: number;
    y1: number;
  };
}

export interface OcrResult {
  rawText: string;
  blocks: OcrBlock[];
  durationMs?: number;
}

export interface ExtractedIdentifier {
  type:
    | "name"
    | "username"
    | "email"
    | "domain"
    | "phone"
    | "organization"
    | "other";
  value: string;
  confidence: number;
  context?: string;
}

export interface VisionAnalysisResult {
  summary: string;
  identifiers: ExtractedIdentifier[];
  raw?: Record<string, unknown>;
  model?: string;
}

export interface AutoGeneratedQuery {
  identifier: string;
  identifierType: ExtractedIdentifier["type"];
  query: string;
}

export interface ImageAnalysisRequest {
  imageUrl?: string;
  imageBase64?: string;
  filename?: string;
  sourceType: ImageSourceType;
}

export interface ImageAnalysisResponse {
  sourceType: ImageSourceType;
  ocr: OcrResult;
  vision: VisionAnalysisResult;
  generatedQueries: AutoGeneratedQuery[];
  relatedResults?: SearchQueryResponse[];
  serpApiRestricted?: boolean;
  serpApiRestrictionReason?: string;
  generatedAt: string;
}

export interface TargetSweepRequest {
  target: string;
  type: SweepTargetType;
  maxResultsPerQuery?: number;
}

export interface SweepSection {
  id: string;
  label: string;
  description: string;
  query: string;
  results: SearchResultItem[];
  totalResults: number;
}

export interface TargetSweepResponse {
  target: string;
  type: SweepTargetType;
  sections: SweepSection[];
  cached: boolean;
  generatedAt: string;
}

export interface SessionHistoryItem {
  id: string;
  label: string;
  kind:
    | "structured-query"
    | "batch-discovery"
    | "image-analysis"
    | "target-sweep";
  input: Record<string, unknown>;
  summary?: string;
  createdAt: string;
  cacheKey?: string;
}

export interface HistoryResponse {
  items: SessionHistoryItem[];
}

export interface ExportRequest {
  format: ExportFormat;
  filename?: string;
  title?: string;
  payload: Record<string, unknown>;
}

export interface ApiErrorResponse {
  error: string;
  details?: string;
  statusCode?: number;
}
